# Generated by Django 5.1.4 on 2025-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_session_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='controllers',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
