# Generated by Django 5.1.4 on 2025-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_session_controllers'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
